function y = coupled_two_leg_qp_signal(x)
%COUPLED_TWO_LEG_QP_SIGNAL Simulink adapter for the shared two-leg QP.
% Spatial layout: tau(6), wrench slack/feasible(12+12), slack norm,
% feasible flag, contact forces(3+3), exit flag, dynamics/contact/wrench
% residual norms, base qdd(6), directional contact residuals(3), common
% wheel error/solve time(3), differential torque(3), common wheel
% acceleration/command/residual(3), friction margins(4), torque margins(6),
% and differential wheel state/acceleration(4). The Simulink interface is
% kept at its deployed 74D width.

[tau, debug] = coupled_two_leg_qp_core(x);
y = [tau; debug.wrenchSlack; debug.wrenchFeasible; ...
    debug.wrenchSlackNorm; double(debug.qpFeasible); ...
    debug.FcLeft; debug.FcRight; debug.exitflag; ...
    norm(debug.dynamicsResidual, inf); ...
    norm(debug.contactAcceleration, 2); ...
    norm(debug.wrenchResidual, inf); debug.qddBase; ...
    debug.contactResidualDirection; debug.xiCommonError; ...
    debug.dxiCommonError; debug.qpSolveTime; debug.tauDifferential; ...
    debug.xiCommonAcceleration; debug.xiCommonCommand; ...
    abs(debug.xiCommonAcceleration - debug.xiCommonCommand); ...
    debug.frictionMargin; ...
    debug.torqueMargin; debug.xiDifferential; debug.dxiDifferential; ...
    debug.xiDifferentialAcceleration; debug.xiDifferentialCommand];
end
