function y = coupled_two_leg_qp_signal(x)
%COUPLED_TWO_LEG_QP_SIGNAL Simulink adapter for the shared two-leg QP.
% Spatial layout: tau(6), wrench slack/feasible(12+12), slack norm,
% feasible flag, contact forces(3+3), exit flag, dynamics/contact/wrench
% residual norms, base qdd(6), differential qdd/command/torque(3+3+3),
% differential contact force(3), friction margins(4), torque margins(6),
% and differential wheel state/acceleration(4).

[tau, debug] = coupled_two_leg_qp_core(x);
y = [tau; debug.wrenchSlack; debug.wrenchFeasible; ...
    debug.wrenchSlackNorm; double(debug.qpFeasible); ...
    debug.FcLeft; debug.FcRight; debug.exitflag; ...
    norm(debug.dynamicsResidual, inf); ...
    norm(debug.contactResidual, inf); ...
    norm(debug.wrenchResidual, inf); debug.qddBase; debug.qddDifferential; ...
    debug.qddDifferentialCommand; debug.tauDifferential; ...
    debug.contactForceDifferential; debug.frictionMargin; ...
    debug.torqueMargin; debug.xiDifferential; debug.dxiDifferential; ...
    debug.xiDifferentialAcceleration; debug.xiDifferentialCommand];
end
