function y = coupled_two_leg_qp_signal(x)
%COUPLED_TWO_LEG_QP_SIGNAL Simulink adapter for the shared two-leg QP.
% Layout: tau(6), wrench slack/feasible(3+3), slack norm, feasible flag,
% contact forces(2+2), exit flag, dynamics residual inf-norm,
% differential qdd/command/torque(3+3+3), differential contact force(2),
% friction margins(2), torque margins(6), and differential wheel-position
% state/acceleration [xi, dxi, ddxi, ddxiCommand](4).

[tau, debug] = coupled_two_leg_qp_core(x);
y = [tau; debug.wrenchSlack; debug.wrenchFeasible; ...
    debug.wrenchSlackNorm; double(debug.qpFeasible); ...
    debug.FcLeft; debug.FcRight; debug.exitflag; ...
    norm(debug.dynamicsResidual, inf); debug.qddDifferential; ...
    debug.qddDifferentialCommand; debug.tauDifferential; ...
    debug.contactForceDifferential; debug.frictionMargin; ...
    debug.torqueMargin; debug.xiDifferential; debug.dxiDifferential; ...
    debug.xiDifferentialAcceleration; debug.xiDifferentialCommand];
end
