function [qd, dqd, ddqd] = wheel_leg_reference(t, traj, leg)
%WHEEL_LEG_REFERENCE Joint reference for the wheel-leg experiment.
%
% The default large-motion experiment uses hip x/y references to generate a
% grounded wheel-center IK trajectory for qh/qk. The upper layer enters the
% dynamics through F_H,des, generated by the floating-base LQR force command.

if nargin < 2 || isempty(traj)
    traj = evalin("base", "traj");
end
if nargin < 3 || isempty(leg)
    leg = evalin("base", "leg");
end

t = double(t);
phase = traj.omega * t + traj.phase;

if isfield(traj, "mode") && string(traj.mode) == "hip_ik"
    hip = evalin("base", "hip");
    [pHRef, dpHRef, ddpHRef] = hip_reference_trajectory(t, hip);

    wheelCenterY = hip.groundTopY + leg.r;
    hipWorldY = hip.baseYOffset + pHRef(2);
    pO = [traj.xO0; wheelCenterY - hipWorldY];
    vO = [0; -dpHRef(2)];
    aO = [0; -ddpHRef(2)];

    reach = norm(pO);
    maxReach = leg.L1 + leg.L2 - 1e-4;
    minReach = abs(leg.L1 - leg.L2) + 1e-4;
    if reach > maxReach || reach < minReach
        error("wheel_leg_reference:HipReferenceOutOfWorkspace", ...
            "Hip reference requires wheel-center reach %.4f m, allowed [%.4f, %.4f] m.", ...
            reach, minReach, maxReach);
    end

    [q_joint, dq_joint, ddq_joint] = wheel_leg_inverse_kinematics(pO, vO, aO, leg);

    xWheel = pHRef(1) + pO(1);
    dxWheel = dpHRef(1) + vO(1);
    ddxWheel = ddpHRef(1) + aO(1);
    xWheel0 = hip.xRef + traj.xO0;

    qw = traj.qw0 - (xWheel - xWheel0) / leg.r ...
        - (sum(q_joint) - traj.thetaWheelBase0);
    dqw = -dxWheel / leg.r - sum(dq_joint);
    ddqw = -ddxWheel / leg.r - sum(ddq_joint);

    qd = [q_joint; qw];
    dqd = [dq_joint; dqw];
    ddqd = [ddq_joint; ddqw];
    return;
elseif isfield(traj, "mode") && string(traj.mode) == "hold"
    qw = traj.qw0;
    dqw = 0;
    ddqw = 0;
    if evalin("base", "exist('hip', 'var')")
        hip = evalin("base", "hip");
        if isfield(hip, "xStep") && isfield(hip, "moveDuration")
            [pRef, dpRef, ddpRef] = hip_reference_trajectory(t, hip);
            qw = traj.qw0 - (pRef(1) - hip.xRef) / leg.r;
            dqw = -dpRef(1) / leg.r;
            ddqw = -ddpRef(1) / leg.r;
        end
    end
    qd = [traj.qJoint0; qw];
    dqd = [zeros(2, 1); dqw];
    ddqd = [zeros(2, 1); ddqw];
    return;
elseif isfield(traj, "xOAmplitude")
    motionPhase = traj.omega * t;
    xO = traj.xO0 + 0.5 * traj.xOAmplitude * (1 - cos(motionPhase));
    dxO = 0.5 * traj.xOAmplitude * traj.omega * sin(motionPhase);
    ddxO = 0.5 * traj.xOAmplitude * traj.omega^2 * cos(motionPhase);
    zO = traj.zORef;

    [q_joint, dq_joint, ddq_joint] = wheel_leg_inverse_kinematics( ...
        [xO; zO], [dxO; 0], [ddxO; 0], leg);
else
    q_joint = traj.offset + traj.amplitude * sin(phase);
    dq_joint = traj.amplitude * traj.omega * cos(phase);
    ddq_joint = -traj.amplitude * traj.omega^2 * sin(phase);
end

kin = wheel_leg_kinematics([q_joint; 0], [dq_joint; 0], ...
    [ddq_joint; 0], leg);

qw = traj.qw0 - (kin.pO(1) - traj.xO0) / leg.r ...
    - (sum(q_joint) - traj.thetaWheelBase0);
dqw = -kin.vO(1) / leg.r - sum(dq_joint);
ddqw = -kin.aO(1) / leg.r - sum(ddq_joint);

qd = [q_joint; qw];
dqd = [dq_joint; dqw];
ddqd = [ddq_joint; ddqw];
end
