function y = common_mode_qp_validation_signal(x)
%COMMON_MODE_QP_VALIDATION_SIGNAL Common-QP output plus validation diagnostics.

[tau, debug] = coupled_two_leg_qp_core(x, "common");
y = [tau; debug.wrenchSlack; debug.wrenchFeasible; ...
    debug.wrenchSlackNorm; double(debug.qpFeasible); ...
    debug.FcLeft; debug.FcRight; debug.exitflag; ...
    debug.dynamicsResidual(:)];
end
